### ISSUE TITLE
gimli_server needs to reuse socket

### ISSUE THREAD

**Issue by second-breakfast** [second-breakfast/gimli#11]
If you run `gimli serve` for awhile and then eventually cancel it, then if you run it again right away you will see this:

```
peregrin@ubuntu:~$ gimli serve
Traceback (most recent call last):
  File "/usr/local/bin/gimli", line 30, in <module>
    g.gimli_server('0.0.0.0', 8001, 3)
  File "/usr/local/lib/python3.6/dist-packages/gimli/gimli.py", line 161, in gimli_server
    fd.bind((host, port))
OSError: [Errno 98] Address already in use
```

After awhile you will be able to run it again, but there seems to be some sort of timeout.

**Comment by second-breakfast** [comment]
Running `netstat | grep 8001` while in this state, I was able to see this:
```
tcp        0      0 localhost:8001          localhost:58748         TIME_WAIT  
tcp        0      0 localhost:8001          localhost:58750         TIME_WAIT  
tcp        0      0 localhost:8001          localhost:58746         TIME_WAIT  
tcp        0      0 localhost:8001          localhost:58752         TIME_WAIT  
tcp        0      0 localhost:8001          localhost:58754         TIME_WAIT  
```
After a bit of research, it looks like this is a common issue web servers face. When we close the connection it may cause the client socket to go into a TIME_WAIT state before shutting down. During this time the socket won't be usable, so we can't do a `gimli serve` again until the timeout finishes. This might be especially noticeable in our case since we are testing the client and server on the same box.

To get around this we can have `gimli_server` set the socket to be reusable.

```python
setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
```
With ABA testing it looks like this fixes it. And after some further research it looks like this is safe to do.
